package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateFromReviewedContract(t *testing.T) {
	spec, err := loadSpec("../../../contracts/tossinvest/openapi.json")
	if err != nil {
		t.Fatal(err)
	}
	ops, err := buildOperations(spec)
	if err != nil {
		t.Fatal(err)
	}
	if len(ops) != 21 {
		t.Fatalf("unexpected operation count: %d", len(ops))
	}

	out := t.TempDir()
	if err := writeGenerated(out, spec, ops); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"catalog_gen.go", "types_gen.go", "client_gen.go"} {
		data, err := os.ReadFile(filepath.Join(out, name))
		if err != nil {
			t.Fatal(err)
		}
		text := string(data)
		if !strings.Contains(text, "Code generated by internal/codegen/tossopenapi") {
			t.Fatalf("%s is missing generated header", name)
		}
	}

	catalog := mustRead(t, filepath.Join(out, "catalog_gen.go"))
	if !strings.Contains(catalog, `OperationCreateOrder`) || !strings.Contains(catalog, `"createOrder"`) {
		t.Fatal("catalog is missing createOrder operation")
	}
	if !strings.Contains(catalog, `LiveTrading: true`) {
		t.Fatal("catalog is missing live trading metadata")
	}

	types := mustRead(t, filepath.Join(out, "types_gen.go"))
	if !strings.Contains(types, "UpperLimitPrice *string") {
		t.Fatal("nullable decimal string was not generated as pointer")
	}
	if !strings.Contains(types, "ConfirmHighValueOrder bool") {
		t.Fatal("oneOf order request fields were not merged")
	}

	client := mustRead(t, filepath.Join(out, "client_gen.go"))
	if !strings.Contains(client, "type Executor interface") {
		t.Fatal("client is missing executor boundary")
	}
	if !strings.Contains(client, "func CreateOrder(") {
		t.Fatal("client is missing raw create order method")
	}
}

func TestGeneratorNameHelpers(t *testing.T) {
	cases := map[string]string{
		"issueOAuth2Token": "IssueOAuth2Token",
		"getKrMarket":      "GetKRMarket",
		"getUsMarket":      "GetUSMarket",
		"orderId":          "OrderID",
		"error_uri":        "ErrorURI",
		"isinCode":         "ISINCode",
	}
	for input, want := range cases {
		if got := goName(input); got != want {
			t.Fatalf("goName(%q)=%q want %q", input, got, want)
		}
	}
}

func mustRead(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}
